# Generated by Django 4.2 on 2023-04-27 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, 'Back-end Developer'), (2, 'Front-end Developer'), (3, 'UX/UI Designer'), (4, 'Marketing specialist'), (5, 'Sales manager'), (6, 'HR manager'), (7, 'Product manager'), (8, 'Project manager'), (9, 'CEO, founders'), (10, 'others')], default=1)),
                ('password', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
