# Generated by Django 4.2 on 2023-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Почта')),
                ('position', models.CharField(choices=[(1, 'Back-end Developer'), (2, 'Front-end Developer'), (3, 'UX/UI Designer'), (4, 'Marketing specialist'), (5, 'Sales manager'), (6, 'HR manager'), (7, 'Product manager'), (8, 'Project manager'), (9, 'CEO, founders'), (10, 'others')], default=10, max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Менеджер')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.DeleteModel(
            name='EmployeeRegister',
        ),
    ]
