# Generated by Django 4.2 on 2023-04-26 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeregister',
            options={'verbose_name': 'Регистрация сотрудника', 'verbose_name_plural': 'Регистрация сотрудников'},
        ),
        migrations.AlterField(
            model_name='employeeregister',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
