# Generated by Django 4.2 on 2023-04-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_employeeregister_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeregister',
            options={},
        ),
        migrations.RenameField(
            model_name='employeeregister',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='employeeregister',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employeeregister',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employeeregister',
            name='position',
            field=models.IntegerField(choices=[(1, 'Back-end Developer'), (2, 'Front-end Developer'), (3, 'UX/UI Designer'), (4, 'Marketing specialist'), (5, 'Sales manager'), (6, 'HR manager'), (7, 'Product manager'), (8, 'Project manager'), (9, 'CEO, founders'), (10, 'others')], default=0),
        ),
        migrations.AlterField(
            model_name='employeeregister',
            name='password',
            field=models.CharField(max_length=18),
        ),
    ]
