# Generated by Django 4.2 on 2023-04-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_employeeregister_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregister',
            name='position',
            field=models.IntegerField(choices=[(1, 'Back-end Developer'), (2, 'Front-end Developer'), (3, 'UX/UI Designer'), (4, 'Marketing specialist'), (5, 'Sales manager'), (6, 'HR manager'), (7, 'Product manager'), (8, 'Project manager'), (9, 'CEO, founders'), (10, 'others')], default=1),
        ),
    ]
