# Generated by Django 4.2 on 2023-05-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Наименование проекта', 'verbose_name_plural': 'Наименование проектов'},
        ),
    ]
