# Generated by Django 4.2 on 2023-05-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена за проект'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Стадия переговоров', 'Стадия переговоров'), ('в разработке', 'В разработке'), ('Завершено', 'Завершено')], max_length=100, verbose_name='Статус'),
        ),
    ]
