# Generated by Django 4.2 on 2023-05-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_price_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('SOM', 'SOM')], default=1, max_length=3, verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
