# Generated by Django 4.2 on 2023-05-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_project_options_alter_project_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
