# Generated by Django 4.2 on 2023-05-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_client_date_updated_alter_project_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключевое слово'),
        ),
    ]
